# Generated by Django 2.0.4 on 2018-08-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chkportinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('IPs', models.CharField(max_length=50)),
                ('ports', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
